### ISSUE TITLE
Failed to select candidates from combobox

### ISSUE THREAD

**Issue by kenhys** [ueno/ibus-kkc#1]
### What is the problem

It is unable to select candidates from combobox by mouse. The candidates are correctly shown but I can't select/click it by mouse. 

For example, "Kana" can't be selected by mouse.

![failed-to-select-candidate-from-combobox](https://cloud.githubusercontent.com/assets/225841/16574933/0de4de9a-42bf-11e6-867f-5191e553c3f5.png)
### How to reproduce it?
1. Just click kkc indicator on system tray, then click 'Preference' menu. It launches ibus-setup-kkc.
2. Click 'Typing rule' combobox. It shows candidates. 
3. Try to click 'Kana' on combobox, but I can't do it.
### Is there any workaround?

Do not use mouse to select it. Just select candidates by key input.
But this is a unexpected behavior.

P.S. Why I say "unexpected behavior", because vala sample supports to select candidates by mouse. https://developer.gnome.org/gnome-devel-demos/stable/combobox.vala.html.en 
### What environment did you verify it?
- Asianux 7 SP1
- libkkc-0.3.1-8.el7
- ibus-kkc-1.5.18-5.el7

To verify whether this behavior depends to ibus-kkc version, I checked another version ans behavior is the same (can't select it by mouse)
- libkkc-0.3.5 (because newer ibus-kkc requires 0.3.4 or later)
- ibus-kkc 1.5.22

and
- libkkc-0.3.5 (because newer ibus-kkc requires 0.3.4 or later)
- ibus-kkc 1.5.22 + 3 patches since 1.5.22 releases (= master)

**Comment by ueno** [comment]
I cannot reproduce it with ibus-kkc-1.5.22-4.fc24 on Fedora 24.  Do you see any errors if you launch it from the command line, with: `/usr/libexec/ibus-setup-kkc`?

**Comment by kenhys** [comment]
Thank you for trying to verify this issue.

There is no critical error messages.

> [kenhys@localhost ~]$ /usr/libexec/ibus-setup-kkc
> Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

One additional information is: It seems that this problem happens on KDE. not Gnome.
But I have no idea why there is such a difference.

**Comment by Shugyousha** [comment]
I tried to reproduce this on Arch with KDE Plasma using
- ibus-kkc 1.5.22-1
- libkkc 0.3.5-1
- plasma-desktop 5.7.2-1

and "ibus-setup-kkc" compiled from git HEAD (at c530c0a2bdc68102397973e0b3fe2262ce6a11d5 ) but could not reproduce this issue (I got the same Gtk-Message warning though).

**Comment by kenhys** [comment]
Thanks for trying to reproduce this issue.

Finally, I can figure out that there is nothing to do with ibus-kkc. This issue is caused by theme - 'oxygen-gtk'.
ref. https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications

There is no problem if another theme - 'Adwaita' is used.

So I close this bug.
